### ISSUE TITLE
div-beta-nightly-2018-03-03 failing to create installation

### ISSUE THREAD

**Issue by alfonsonishikawa** [DIVGAMES/DIV-Games-Studio#30]
I have a game that the stable version (http://div-arena.co.uk/downloads/) successfully creates the installation package but the music is not played. I am trying to create the installation package with div-beta-nightly-2018-03-03 but it creates a 0bytes EXE, and a ZIP with the following files with 0 bytes sizes:

- Executable.EXE
- libgcc_s_dw2-1.dll
- libmad-0.dll
- libSDL_mixer-1-2-0.dll
- DSL_net.dll
- zlib1.dll

I attach the game to allow to reproduce the issue.

Thank you!

[boxing.zip](https://github.com/DIVGAMES/DIV-Games-Studio/files/1866286/boxing.zip)

**Comment by MikeDX** [comment]
Thanks for the file. I'll take a look and see what is going on. Could be a file is missing from that nightly build.

Does it work/run in any older beta version?

**Comment by CicTec** [comment]
Hello @alfonsonishikawa,

The latest beta 13 and nightlybuilds have a known problem with installations etc...

Try the latest stable version from this link:
http://div-arena.co.uk/forum2/viewthread.php?tid=246

To see if it solves your problem until the nightlybuild is fixed.

**Comment by alfonsonishikawa** [comment]
I made a mistake in my first description. The package gets created in the stable version (where the music is not played), but not in the nightly (were the music works). Thank you!!

**Comment by CicTec** [comment]
Hello @alfonsonishikawa,

So, the beta 13 has problems with the audio in the installation, while in the nightlybuild the audio works, but does it have installation problems?

Did you try the latest link version? does it give you the same problems?

Thanks for the feedbacks.

**Comment by alfonsonishikawa** [comment]
> So, the beta 13 has problems with the audio in the installation, while in the nightlybuild the audio works, but does it have installation problems?

At least with the project I attached at the beginning:

- Beta 13 lacks music even when running within the IDE. The creation of the installation package succeds but still no music is heard (sound effects works).
- div-beta-nightly-2018-03-03-f57f75c9fe-win32 music works, but the the creation of the installation package fails.

Thanks to you all.

**Comment by CicTec** [comment]
Ok thanks for the feedback.

If possible try please the update 17.09.03 from here:
http://div-arena.co.uk/forum2/viewthread.php?tid=246

To see if it solve you problems.

**Comment by alfonsonishikawa** [comment]
> If possible try please the update 17.09.03 from here:
> http://div-arena.co.uk/forum2/viewthread.php?tid=246
> 
> To see if it solve you problems.

Hi!

With update 17.09.03 happens the same as the stable version: it creates the package but the music is not played. I even added the .S3M to the .zip package contents and executed that version.

Thank you!

**Comment by CicTec** [comment]
Hi,

Ok, I've downloaded your attachment boxing.zip to see what could happen, thanks again for the feedback.

**Comment by CicTec** [comment]
Hi @alfonsonishikawa,

Please download and try when possible the new build 18.04.26 from here:
http://div-arena.co.uk/forum2/viewthread.php?tid=246

This build should fix your problem with S3M playing and installer.

**Comment by alfonsonishikawa** [comment]
Hi, @CicTec . Sorry for the delay! (I have been very busy :S )

It works like a charm :) Thank you!!

**Comment by CicTec** [comment]
Hi @alfonsonishikawa, no problem. :)

Great, thanks for the feedback. ;)
