### ISSUE TITLE
Any chance for Raspbian (Buster) binary? 

### ISSUE THREAD

**Issue by varna9000** [DIVGAMES/DIV-Games-Studio#31]
Hi, would it be easy to compile it directly on the RPi? I see instruction only for cross compilation and I'm not that proficient in building from source..

**Comment by MikeDX** [comment]
This should compile easily on the Pi, just compile as if it was for generic linux natively. I think I have done this in the past but I wouldnt guarantee the state of a build from master at this point.

**Comment by varna9000** [comment]
@MikeDX Thanks, Mike. I'll surely try and come back with the result.
